Feature/xinyi/usercontroller
DouMaokang/EventSG-backend pull request #2
Opened 2020-03-20 16:44 UTC by SarahChane98

Have tested on Postman and all methods in api worked well.

2020-03-22 02:28 UTC, edyq requested changes
1. 豆豆说那个database的jdbc-url大家都要交demodb 【当然我不知道他会不会改。。】
2. 豆豆说sql table要所有create table的statement都放到一个file里，俺不是很懂，但是如果分开放是working的话，应该也星？idk

2020-03-22 02:52 UTC, SarahChane98 commented
> 1. 豆豆说那个database的jdbc-url大家都要交demodb 【当然我不知道他会不会改。。】
> 2. 豆豆说sql table要所有create table的statement都放到一个file里，俺不是很懂，但是如果分开放是working的话，应该也星？idk

ok好我改一下 我以为demodb是个demo名字哈哈

2020-03-22 03:07 UTC, SarahChane98 reviewed
fixed as requested by the comments.

2020-03-23 01:25 UTC, edyq commented on src/main/java/eventsg/backend/controller/UserController.java
> +    private final UserServiceImpl userService;
doudou says we need to pass in the UserService interface here, then implement the UserService interface with UserServiceImpl

2020-03-23 03:17 UTC, closed without merging